# Generated by Django 4.2.2 on 2023-07-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flight_destinaion_alter_flight_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destinaion',
            new_name='destination',
        ),
    ]
